### ISSUE TITLE
Custom language grammar usage question

### ISSUE THREAD

**Issue by ghost** [antlr/groom#45]
Hello, 

This may be obvious after reading the docs, but I am having issues figuring out how to use this tool for a custom language grammar. Is it as simple as importing the compiled codebuff .JAR and calling the following:

```java
org.antlr.codebuff.Tool.format(new org.antlr.codebuff.misc.LangDescriptor("MyLang",
                                        "corpus/path/to/mylang/examples",
                                        ".mylang", MyLangLexer.class, MyLangParser.class, "mylang_file", 4,
                                        MyLang.LINE_COMMENT),
                                        "source.mylang",
                                        "destination.mylang");
```

This does format and output to my destination file, but it looks nothing like the example files.

Or do I need to train the model for my language in the codebuff project?

Any help is appreciated!

**Comment by parrt** [comment]
hi. sorry but my mind has drifted away to new areas and I can't remember the details!

**Comment by ghost** [comment]
No worries -- I think I have it figured out now!

Awesome tool by the way!

**Comment by parrt** [comment]
Thanks. hoping to do an improved version someday
