### ISSUE TITLE
Bump Antlr4 Runtime dependency

### ISSUE THREAD

**Issue by onur-eken-celonis** [antlr/groom#46]
Hi team 👋🏼 

Codebuff is great! Thanks for your work. We want to use it in our project in which we use the most recent antlr4 compiler + runtime environment. Codebuff uses a much older version, could you bump that?

Also do you consider publishing Codebuff to the maven central repository?

Best

**Comment by parrt** [comment]
Hi!  Thanks for the note. Unfortunately I haven't been able to do anything with this project as I'm stuck as an administrator now. You should be able to simply update the antlr version and it would work.  I think this is still more the research level than production level so you might take that into consideration.
